{
 "title": "Verbrauch",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Stromverbrauch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Interval-Verbrauch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \"inserted_on\"   AT TIME ZONE 'UTC' AT TIME ZONE 'GMT'  AS \"time\", powercurr AS \"Stromnetz\",powerout AS \"Ins Stromnetz\"  FROM home   WHERE inserted_on BETWEEN '${__from:date:iso}' AND '${__to:date:iso}'\n ORDER BY inserted_on desc"
    }
   ]
  },
  {
   "title": "Solarzellen",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n\tto_timestamp(dhzgqq.eco_20_1_utctime),\n\t(dhzgqq.eco_20_1_pv1inputwatts + dhzgqq.eco_20_1_pv2inputwatts)/ 10 as \"Generieren\" ,\n\tabs(least( dhzgqq.eco_20_1_batinputwatts::float / 10, 0)) as \"Batterieinput\",\n\tabs(greatest( dhzgqq.eco_20_1_batinputwatts::float / 10, 0)) as \"Batterienutzung\",\n\tdhzgqq.eco_20_1_genewatt / 10 as \"Hausnetzeingang\",\n\tabs(dhzgqq.eco_20_1_gridconswatts::float / 10) as \"Stromnetz\",\n\teco_20_1_invdemandwatts / 10 as \"Bedarf\",\n\th.powercurr as \"Verbrauch\",\n\th.powerout as \"Einspeisung\"\nfrom\n\tdevice_quota dhzgqq, home h\n\twhere dhzgqq.eco_serial_number = upper('hw51zeh49g9q1664')\norder by\n\tdhzgqq.eco_timestamp desc, \"time\" desc\nlimit 1"
    }
   ]
  },
  {
   "title": "24h Verbrauch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT inserted_on as time, powercurr FROM home WHERE   inserted_on >= NOW() - '1 day'::INTERVAL order by inserted_on desc "
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select * from (select\n\td2.eco_timestamp,\n\t\td2.eco_bms_bmsstatus_actsoc as \"Batterie Balkon\"\nfrom\n\tdevice_quota d2\n\twhere d2.eco_serial_number  = upper('r351zeb5pgb91424')\norder by\n\td2.eco_timestamp desc\nlimit 1)\n"
    },
    {
     "rawSql": "\nselect * from (select\n\td2.eco_timestamp,\n\t\td2.eco_bms_bmsstatus_actsoc as \"Batterie Büro\"\nfrom\n\tdevice_quota d2\n\twhere d2.eco_serial_number  = upper('r331zeb5sgbu0300')\norder by\n\td2.eco_timestamp desc\nlimit 1)\n"
    }
   ]
  },
  {
   "title": "Einspeisung in kw",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM (SELECT 'Einspeisung in range' as name,CAST(SUM(powerout) AS float) / CAST(1000 AS float) as \"PowerOut\" FROM home WHERE time BETWEEN '${__from:date:iso}' AND '${__to:date:iso}'\nunion SELECT 'Einspeisung/Monat' as name,CAST(SUM(powerout) AS float) / CAST(1000 AS float) as \"PowerOut\" FROM home WHERE to_char(time, 'YYYY-MM') = to_char(now(), 'YYYY-MM')\nUNION SELECT 'Einspeisung/2025' as name,CAST(SUM(powerout) AS float) / CAST(1000 AS float) as \"PowerOut\" FROM home WHERE \"time\" > to_date('2025','YYYY')\nunion SELECT 'Einspeisung/Gesamt' as name,CAST(SUM(powerout) AS float) / CAST(1000 AS float) as PowerOut FROM home) ORDER BY \"PowerOut\" ASC"
    }
   ]
  },
  {
   "title": "Mögl.Jahresverbrauch",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n\t(ce.total-mx.total)/DATE_PART('doy',now())* EXTRACT(DOY from cast(TO_CHAR(now(),'yyyy-12-31 20:00:00') as timestamp))-(ce.total-mx.total) as overall,\n\tce.total-mx.total as current\nfrom\n\t(\n\tselect\n\t\ttotal,\n\t\tinserted_on\n\tfrom\n\t\thome\n\torder by\n\t\tinserted_on desc\n\tlimit 1) ce,\n\t(\n\tselect\n\t\ttotal as total\n\tfrom\n\t\thome\n\twhere\n\t\tdate_part('year', time) = date_part('year', now())\n\torder by\n\t\ttime\n\tlimit 1) mx\norder by\n\tinserted_on"
    }
   ]
  },
  {
   "title": "Batteriekapazität",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 5, "y": 18 },
   "targets": [
    {
     "rawSql": "select\n\teco_timestamp at time zone 'europe/berlin',\n\teco_bms_bmsstatus_actsoc  as \"Batteriestand Balkon\"\nfrom\n\tdevice_quota\nwhere\n\teco_timestamp at time zone 'europe/berlin' between '${__from:date:iso}' and '${__to:date:iso}'\n\tand eco_serial_number = UPPER('R351ZEB5PGB91424')\norder by\n\teco_timestamp desc"
    },
    {
     "rawSql": "select\n\teco_timestamp at time zone 'europe/berlin',\n\teco_bms_bmsstatus_actsoc as \"Batteriestand Büro\"\nfrom\n\tdevice_quota\nwhere\n\teco_timestamp at time zone 'europe/berlin' between '${__from:date:iso}' and '${__to:date:iso}'\n\tand  eco_serial_number = upper('r331zeb5sgbu0300')\norder by\n\teco_timestamp desc"
    }
   ]
  },
  {
   "title": "Hochrechnung Jahresverbrauch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (ce.total-mx.total)/DATE_PART('doy',now())* EXTRACT(DOY from cast(TO_CHAR(now(),'yyyy-12-31 20:00:00') as timestamp))  from (SELECT total,inserted_on FROM home order by inserted_on DESC LIMIT 10000) ce, (select total as total from home where date_part('year',time) = date_part('year',now()) order by time limit 1) mx order by inserted_on"
    }
   ]
  },
  {
   "title": "Batterie-Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select\n\teco_timestamp,\n\teco_20_1_pv1temp / 10 as pv1temp,\n\teco_20_1_pv2temp / 10 as pv2temp,\n\teco_20_1_llctemp / 10 as llctemp,\n\teco_20_1_battemp::float / 10 as battemp\nfrom\n\tdevice_quota\nwhere\n\teco_timestamp between '${__from:date:iso}' and '${__to:date:iso}'\n\tand eco_serial_number = UPPER('hw51zeh49g9q1664')"
    }
   ]
  }
 ]
}